apiVersion: v1
kind: Service
metadata:
  name: htmrt-backend
spec:
  type: NodePort
  selector:
    app: htmrt-backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmrt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmrt-backend
  template:
    metadata:
      labels:
        app: htmrt-backend
    spec:
      containers:
      - name: server
        image: gcr.io/htmrt-260621/htmrt-backend:75c1077
        ports:
        - containerPort: 8080
        env:
        - name: RUN_PORT
          value: "8080"
        - name: FLASK_DEBUG
          value: 'True'
        - name: ENV_NAME
          value: 'PROD'