apiVersion: v1
kind: Service
metadata:
  name: htmrt-frontend
spec:
  type: LoadBalancer
  loadBalancerIP: "104.198.104.13"
  selector:
    app: htmrt-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmrt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmrt-frontend
  template:
    metadata:
      labels:
        app: htmrt-frontend
    spec:
      containers:
      - name: server
        image: gcr.io/htmrt-260621/htmrt-frontend:044822d
        ports:
        - containerPort: 80
        env:
        - name: RUN_PORT
          value: "80"
        - name: FLASK_DEBUG
          value: 'True'
      restartPolicy: Always